config/routes.rb
Rails.application.routes.draw do
  resources :movimentacaos
  resources :operacaos
  resources :produtos
  resources :unidades
  resources :grupo_produtos
  resources :pessoas
  resources :enderecos
  resources :cidades
  resources :estados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  validates :nome, presence: true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cidade
  validates :cep, :logradouro, :bairro, :complemento, presence: true
end

app/models/estado.rb
class Estado < ApplicationRecord
  validates :uf, presence: true
  validates_length_of :uf, maximum: 2
  validates :uf, uniqueness: true
end

app/models/grupo_produto.rb
class GrupoProduto < ApplicationRecord
  validates :nome, presence: true
  validates :nome, uniqueness: true
end

app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  belongs_to :pessoa
  belongs_to :operacao
  belongs_to :produto


  validates :quantidade, numericality: { greater_than: 0 }
  validates :data, :quantidade, :pessoa, :operacao, :produto, presence: true
  validates :data, :pessoa, :operacao, uniqueness: true

  scope :por_operacao, lambda { |produto, data, operacao|
  where('produto_id = ? and data <= ? and operacao_id = ?',
        produto, data, operacao).sum(:quantidade)}
        
end

app/models/operacao.rb
class Operacao < ApplicationRecord
  enum tipo: { venda: 0, compra: 1, devolucao_venda: 2, devolucao_compra: 3 }

  validates :tipo, :descricao, presence: true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  enum tipo: { cliente: 0, fornecedor: 1 }

  validates :nome, :documento, :endereco_id, :tipo, presence: true
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :unidade
  belongs_to :grupo_produto

  validates :nome, presence: true
  validates :nome, uniqueness: true
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  validates :sigla, :descricao, presence: true
  validates :sigla, uniqueness: true
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:estado_id, :nome)
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:uf)
    end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :documento)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/grupo_produtos_helper.rb
module GrupoProdutosHelper
end

app/helpers/movimentacaos_helper.rb
module MovimentacaosHelper
end

app/helpers/operacaos_helper.rb
module OperacaosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/cidades/_form.html.erb
<%= form_with(model: cidade, local: true) do |form| %>
  <% if cidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cidade.errors.count, "error") %> prohibited this cidade from being saved:</h2>

      <ul>
      <% cidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :estado_id %>
    <%= form.text_field :estado_id %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cidades/edit.html.erb
<h1>Editing Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Show', @cidade %> |
<%= link_to 'Back', cidades_path %>

app/views/cidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cidades</h1>

<table>
  <thead>
    <tr>
      <th>Estado</th>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cidades.each do |cidade| %>
      <tr>
        <td><%= cidade.estado %></td>
        <td><%= cidade.nome %></td>
        <td><%= link_to 'Show', cidade %></td>
        <td><%= link_to 'Edit', edit_cidade_path(cidade) %></td>
        <td><%= link_to 'Destroy', cidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cidade', new_cidade_path %>

app/views/cidades/new.html.erb
<h1>New Cidade</h1>

<%= render 'form', cidade: @cidade %>

<%= link_to 'Back', cidades_path %>

app/views/cidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Estado:</strong>
  <%= @cidade.estado %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cidade.nome %>
</p>

<%= link_to 'Edit', edit_cidade_path(@cidade) %> |
<%= link_to 'Back', cidades_path %>

app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uf %>
    <%= form.text_field :uf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editing Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Show', @estado %> |
<%= link_to 'Back', estados_path %>

app/views/estados/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table>
  <thead>
    <tr>
      <th>Uf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= estado.uf %></td>
        <td><%= link_to 'Show', estado %></td>
        <td><%= link_to 'Edit', edit_estado_path(estado) %></td>
        <td><%= link_to 'Destroy', estado, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estado', new_estado_path %>

app/views/estados/new.html.erb
<h1>New Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Back', estados_path %>

app/views/estados/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uf:</strong>
  <%= @estado.uf %>
</p>

<%= link_to 'Edit', edit_estado_path(@estado) %> |
<%= link_to 'Back', estados_path %>

app/views/pessoas/_form.html.erb
<%= form_with(model: pessoa, local: true) do |form| %>
  <% if pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :documento %>
    <%= form.text_field :documento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Documento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.documento %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New Pessoa</h1>

<%= render 'form', pessoa: @pessoa %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @pessoa.documento %>
</p>

<%= link_to 'Edit', edit_pessoa_path(@pessoa) %> |
<%= link_to 'Back', pessoas_path %>