config/routes.rb
Rails.application.routes.draw do
  resources :movimentacaos
  resources :operacaos
  resources :produtos
  resources :unidades
  resources :grupo_produtos
  resources :pessoas
  resources :enderecos
  resources :cidades
  resources :estados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cidade.rb
class Cidade < ApplicationRecord
  belongs_to :estado
  validates :nome, presence: true
end

app/models/endereco.rb
class Endereco < ApplicationRecord
  belongs_to :cidade
  validates :cep, :logradouro, :bairro, :complemento, presence: true
end

app/models/estado.rb
class Estado < ApplicationRecord
  validates :uf, presence: true
  validates_length_of :uf, maximum: 2
  validates :uf, uniqueness: true
end

app/models/grupo_produto.rb
class GrupoProduto < ApplicationRecord
  validates :nome, presence: true
  validates :nome, uniqueness: true
end

app/models/movimentacao.rb
class Movimentacao < ApplicationRecord
  belongs_to :pessoa
  belongs_to :operacao
  belongs_to :produto


  validates :quantidade, numericality: { greater_than: 0 }
  validates :data, :quantidade, :pessoa, :operacao, :produto, presence: true
  validates :data, :pessoa, :operacao, uniqueness: true

  scope :por_operacao, lambda { |produto, data, operacao|
  where('produto_id = ? and data <= ? and operacao_id = ?',
        produto, data, operacao).sum(:quantidade)}
        
end

app/models/operacao.rb
class Operacao < ApplicationRecord
  enum tipo: { venda: 0, compra: 1, devolucao_venda: 2, devolucao_compra: 3 }

  validates :tipo, :descricao, presence: true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  enum tipo: { cliente: 0, fornecedor: 1 }

  validates :nome, :documento, :endereco_id, :tipo, presence: true
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :unidade
  belongs_to :grupo_produto

  validates :nome, presence: true
  validates :nome, uniqueness: true
end

app/models/unidade.rb
class Unidade < ApplicationRecord
  validates :sigla, :descricao, presence: true
  validates :sigla, uniqueness: true
end

app/controllers/cidades_controller.rb
class CidadesController < ApplicationController
  before_action :set_cidade, only: [:show, :edit, :update, :destroy]

  # GET /cidades
  # GET /cidades.json
  def index
    @cidades = Cidade.all
  end

  # GET /cidades/1
  # GET /cidades/1.json
  def show
  end

  # GET /cidades/new
  def new
    @cidade = Cidade.new
  end

  # GET /cidades/1/edit
  def edit
  end

  # POST /cidades
  # POST /cidades.json
  def create
    @cidade = Cidade.new(cidade_params)

    respond_to do |format|
      if @cidade.save
        format.html { redirect_to @cidade, notice: 'Cidade was successfully created.' }
        format.json { render :show, status: :created, location: @cidade }
      else
        format.html { render :new }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cidades/1
  # PATCH/PUT /cidades/1.json
  def update
    respond_to do |format|
      if @cidade.update(cidade_params)
        format.html { redirect_to @cidade, notice: 'Cidade was successfully updated.' }
        format.json { render :show, status: :ok, location: @cidade }
      else
        format.html { render :edit }
        format.json { render json: @cidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cidades/1
  # DELETE /cidades/1.json
  def destroy
    @cidade.destroy
    respond_to do |format|
      format.html { redirect_to cidades_url, notice: 'Cidade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cidade
      @cidade = Cidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cidade_params
      params.require(:cidade).permit(:estado_id, :nome)
    end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estado_params
      params.require(:estado).permit(:uf)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :unidade_id, :grupo_produto_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cidades_helper.rb
module CidadesHelper
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/grupo_produtos_helper.rb
module GrupoProdutosHelper
end

app/helpers/movimentacaos_helper.rb
module MovimentacaosHelper
end

app/helpers/operacaos_helper.rb
module OperacaosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto, local: true) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :unidade_id %>
    <%= form.text_field :unidade_id %>
  </div>

  <div class="field">
    <%= form.label :grupo_produto_id %>
    <%= form.text_field :grupo_produto_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Show', @produto %> |
<%= link_to 'Back', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Unidade</th>
      <th>Grupo produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.unidade %></td>
        <td><%= produto.grupo_produto %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produto', new_produto_path %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>

<%= link_to 'Back', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Unidade:</strong>
  <%= @produto.unidade %>
</p>

<p>
  <strong>Grupo produto:</strong>
  <%= @produto.grupo_produto %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>